### ISSUE TITLE
conflict in the official documentation

### ISSUE THREAD

**Issue by kvsravindrareddy** [graphql-java/tutorials#10]
I could see there is a conflict in the official documentation.

this dosen't work with http://localhost:8080/graphql instead 
http://localhost:8080/graphiql

basically i missing here.

Reference document https://www.graphql-java.com/tutorials/getting-started-with-spring-boot/

**Comment by jayapradam** [comment]
http://localhost:8080/graphiql this is also not working for me. Getting "HTTP Status 400 – Bad Request"

**Comment by dondonz** [comment]
Closing this old issue as the tutorial has since been rewritten to use Spring for GraphQL.
