### ISSUE TITLE
Cannot integreate with graphql-java verion 15.0

### ISSUE THREAD

**Issue by SeabiscuitCZX** [graphql-java/tutorials#11]
There is an issue in GraphQLInbocationDaata class,  in Graphql version 15.0, the Assert.assertNotNull method was been changed. 
the second parameter type was changed to Supplier<String> msg, not String any more. 
fixed code:
public GraphQLInvocationData(String query, String operationName, Map<String, Object> variables) {
        this.query = Assert.assertNotNull(query, () -> "query must be provided");
        this.operationName = operationName;
        this.variables = variables != null ? variables : Collections.emptyMap();
    }

**Comment by dondonz** [comment]
Closing this old issue as the tutorial has since been rewritten to use Spring for GraphQL and a much later version of graphql-java
