### ISSUE TITLE
Thanks.. 

### ISSUE THREAD

**Issue by stayhungryStayCalm** [graphql-java/tutorials#14]
Thanks for sharing the sample code here.. If you could correct the below method by adding the prefix TypeRuntimeWiring, it will help starters like me.
 
private RuntimeWiring buildWiring() {
        return RuntimeWiring.newRuntimeWiring()
                .type(**TypeRuntimeWiring**.newTypeWiring("Query")
                        .dataFetcher("bookById", graphQLDataFetchers.getBookByIdDataFetcher()))
                .type(**TypeRuntimeWiring**.newTypeWiring("Book")
                        .dataFetcher("author", graphQLDataFetchers.getAuthorDataFetcher()))
                .build();
    }

**Comment by dondonz** [comment]
Closing this issue as the tutorial has been rewritten with Spring for GraphQL, which automatically wires up datafetchers
