### ISSUE TITLE
Whitelabel Error Page

### ISSUE THREAD

**Issue by HuakunShen** [graphql-java/tutorials#17]
Got a Whitelabel Error Page after starting the application
![image](https://user-images.githubusercontent.com/33727687/155684456-d8456654-e835-4844-a833-8b35889c60b2.png)

**Comment by qstommyshu** [comment]
Got the same error

**Comment by Raghav2211** [comment]
@HuakunShen  @qstommyshu I just tried with different repository and it's work fine https://github.com/Raghav2211/graphql-java-spring-boot-example
Let me know if works for you 
Cheers!!

**Comment by harpunfiskeren** [comment]
make sure your ´schema.graphqls´ is spelled correctly.
make sure to use the correct URL ´localhost:7000/graphiql' (This seems to be the issue in your case)

**Comment by dondonz** [comment]
Thanks for the help - closing this older issue for now.
