### ISSUE TITLE
how to insert delete and upupdate

### ISSUE THREAD

**Issue by Rgoogle** [graphql-java/tutorials#19]
the tutorials is query .but insert delete and update is no say.

**Comment by dondonz** [comment]
That's a good idea, initially my thinking was to keep the tutorial as small as possible, and demonstrate the service working end to end. Perhaps you already saw this, to see examples of mutations (which would include adding, editing, and deleting data), see the official documentation: https://docs.spring.io/spring-graphql/reference/controllers.html
