### ISSUE TITLE
Can't visit index page

### ISSUE THREAD

**Issue by nobody2014100** [graphql-java/tutorials#2]
after i run the application, http://localhost:8080/graphql can't be visit.
![image](https://user-images.githubusercontent.com/8716969/52631359-9602a180-2ef9-11e9-8383-46c1cb656ddb.png)

**Comment by johnliucn925** [comment]
As you see in the error message: query is not provided. You need download graphql playground to play with it.

**Comment by nobody2014100** [comment]
last night i tried again, then i find out i need a tool **graphql playground** too visit that endpoint. thank you for your answer.
