### ISSUE TITLE
请教些问题

### ISSUE THREAD

**Issue by kscMaster** [graphql-java/tutorials#20]
1. 事实上在实际项目中，GraphQL只是一个中间层，SQL还是要后端去写的，但是要写得很通用，才能支持前端各种查询吗？
2. ORM层都要写到对象里去查询数据吗？

**Comment by dondonz** [comment]
Hello, as this is a general question about data modelling and not specifically about the tutorial contents, I will close out the issue.

I hope you managed to find the answer!
