### ISSUE TITLE
Question: DataFetcher and RuntimeWiring vs GraphQLQueryResolver

### ISSUE THREAD

**Issue by SnuK87** [graphql-java/tutorials#4]
I just started with graphql and have a question about this tutorial.

I don't really see the purpose of the `GraphQLProvider` class. Especially the method `buildWiring()`. As far as I can see the `graphql-spring-boot-starter` is doing the initialization and wiring automagically.

The following code is working fine for me:

```
@Component
@RequiredArgsConstructor
public class Query implements GraphQLQueryResolver {

	private final AuthorRepository authorRepo;
	private final BookRepository bookRepo;

    public Author getAuthor(Long id) {
    	return authorRepo.findById(id).orElse(null);
    }

    public Book getBook(Long id) {
    	return bookRepo.findById(id).orElse(null);
    }
}
```

Is there any benift of defining the DataFetchers manually? Or is this tutorial just outdated?

**Comment by ualter** [comment]
Yes, perhaps it is outdated, here https://dzone.com/articles/a-beginners-guide-to-graphql-with-spring-boot another tutorial, more updated using the technique you described.

**Comment by Marx2** [comment]
While I agree that this tutorial is outdated, I don't agree that manual wiring has no sense. It's not possible to make async resolvers.

**Comment by dondonz** [comment]
Closing this old issue as since the tutorial has been updated to use Spring for GraphQL
