### ISSUE TITLE
this does not work 404 error

### ISSUE THREAD

**Issue by josh123a123** [graphql-java/tutorials#5]
just cloning this and running it results in 
{
  "timestamp": "2019-08-01T17:35:11.276+0000",
  "status": 404,
  "error": "Not Found",
  "message": "No message available",
  "path": "/graphql"
}

**Comment by Marx2** [comment]
I can confirm, that with new graphql-java libraries this configuration doesn't work anymore - /graphql endpoint is not accessible

**Comment by dezzak** [comment]
In my case, I hadn't included the dependency `graphql-java-spring-boot-starter-webmvc`. It worked for me after I included it (using mvn) in my case:
```
<dependency>
        <groupId>com.graphql-java</groupId>
        <artifactId>graphql-java-spring-boot-starter-webmvc</artifactId>
        <version>2019-06-24T11-47-27-31ab4f9</version>
</dependency>
```

**Comment by gavin-haynes-grow** [comment]
It should work if you specify query params e.g.

`http://localhost:8080/graphql?query=%7BbookById(id%3A%20%22book-1%22)%20%7B%20id%20%7D%7D`

query is `encodeURIComponent("{bookById(id: \"book-1\") { id }}")`

**Comment by davindersingh0** [comment]
It did not work 404 error

**Comment by lihao5257** [comment]
@dezzak  
That solution also worked for me . Thank you !

**Comment by wanghe9011** [comment]
@gavin-haynes-grow Well Done. Thank you !

**Comment by lsarkisov** [comment]
This works for me:

<img width="1440" alt="Снимок экрана 2021-04-17 в 4 59 19 PM" src="https://user-images.githubusercontent.com/42303274/115117358-68648780-9f9e-11eb-82c2-c01c18a3937e.png">

**Comment by KaiJiaBrother** [comment]
> It should work if you specify query params e.g.
> 
> `http://localhost:8080/graphql?query=%7BbookById(id%3A%20%22book-1%22)%20%7B%20id%20%7D%7D`
> 
> query is `encodeURIComponent("{bookById(id: \"book-1\") { id }}")`

I agree, parameter 'query' is required.

**Comment by dondonz** [comment]
Closing this old issue as since then the tutorial has been rewritten to use Spring for GraphQL
