### ISSUE TITLE
Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by filosofisto** [graphql-java/tutorials#8]
Just have started server, execute with GraphQL Playground as suggeted and it does not works.
Error:

Unexpected token < in JSON at position 0

![image](https://user-images.githubusercontent.com/1119247/68701607-eb8ddc80-0565-11ea-91a6-52390ce2e2be.png)

Any help?

Best,
Eduardo

**Comment by Mannik01** [comment]
Hi Eduardo,

This may be because some of the imports in the classes were from incorrect sources, for example, ImmutableMap, Resources and Charsets. So, please make sure the imports are correct.

This issue usually arises when there is an error while parsing JSON from the server response.

-Mandip

**Comment by dondonz** [comment]
Closing this old issue as the tutorial has since been rewritten to use Spring for GraphQL. Hopefully you were able to resolve the issue
